// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpvywtsldvdsovsdxamn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwdnl3dHNsZHZkc292c2R4YW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNDIyMDcsImV4cCI6MjA2MjkxODIwN30.rWwQc9mebEK1ahbYoZ-gDHamBBjDidAnJCoLlXaREYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);